zookeeper:
  build: ./zookeeper
  container_name: zookeeper
  ports:
  - "2181:2181"
  - "2888:2888"
  - "3888:3888"
  - "9998:9998"
  environment:
    ZK_DATADIR: /var/log/zookeeper

registrator:
  command: zookeeper://zookeeper:2181/services
  image: gliderlabs/registrator:master
  container_name: registrator
  links:
  - zookeeper
  volumes:
  - "/var/run/docker.sock:/tmp/docker.sock"

service1:
  image: nginxdemos/hello:latest
  container_name: service1
  labels:
    SERVICE_NAME: service1
    SERVICE_TAGS: production
  ports:
  - "8081:80"

service2:
  image: nginxdemos/hello:latest
  container_name: service2
  labels:
    SERVICE_NAME: service2
    SERVICE_TAGS: production
  ports:
  - "8082:80"
